$(document).ready(function(){
    $("#signupForm").validate({
        rules:{
            emailorph:{
                required:true,
                minlength:10,
                maxlength:20,
                email:true
            },
            password:{
                required:true,
                minlength:8,
                maxlength:20
            },
        },
        //messages:{
            //emailorph:{
                //required:"Enter Mail ID or Phone number"
            //}
        //}
    })
})